name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v3

    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: 'Install dependencies'
      run: npm install

    - name: 'Build Application'
      run: npm run build

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'  # Change to your deployment slot if needed
        package: '.'
